language: python
python:
  - 2.7.15
cache: pip
install:
  - pip install -r requirements.txt
script:
  - openapi-spec-validator source/resources/collections/swagger2.yaml --schema 2.0
  - openapi-spec-validator source/resources/collections/openapi3.yaml --schema 3.0
  - make alldocs

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: build/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
