language: python

python:
  - 3.7
  - 3.8
cache: pip

before_install:
  - cd source/resources/examples/typescript
  - npm install
#  - npm run lint renable once npm run style:fix is executed
# include tsc compile!
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
script:
  - make gettext
deploy:
  - provider: script
    skip_cleanup: true
    script: bash travis/transifex.sh
    on:
      branch: main
      python: 3.7
  - provider: script
    skip_cleanup: true
    script: bash travis/deploy.sh
    on:
      branch: main
      python: 3.7
